version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 8000:8000
    depends_on:
      - database
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
  database:
    image: mongo:latest